### ISSUE TITLE
Can snapchange fuzz VM devices (eg:fortigate, Citrix adc)? 

### ISSUE THREAD

**Issue by madjohn698** [awslabs/snapchange#22]
Can snapchange fuzz virtual machine devices?eg:Citrix adc, fortigate and so on. if sure, can you provide a example or give some references?

**Comment by corydu** [comment]
Assuming we had a snapshot (physical memory dump and register state) of a target process on one of these devices, snapchange should be able to fuzz it (assuming x86 architecture). Fuzzing with snapchange doesn't require a snapshot to be created with the example qemu-based snapshot mechanism.

There is some [documentation](https://github.com/awslabs/snapchange/blob/main/docs/VIRTUALBOX_SNAPSHOT.md) on how to obtain a snapshot using Virtualbox, which might be the easier option in this case. Even if Virtualbox wouldn't work, the process around obtaining a snapshot using Virtualbox could be applied to however the virtual device is launched. I think getting a snapshot of one of the devices might be tricky, but doable for sure.

**Comment by madjohn698** [comment]
@corydu , Thanks, I think this is a very interesting thing. I once wanted to use mechanism of qemu's hook function for testing, but the effect was not ideal. The interaction of these virtual devices is more complicated, and the simple hook mechanism has many problems.
